// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

type FactIntervention struct {
	ID         string    `json:"id"`
	Employee   *Employee `json:"employee"`
	BuildingID int       `json:"building_id"`
	Result     string    `json:"result"`
	Status     string    `json:"status"`
	EmployeeID string    `json:"employeeId`
}
